kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${project.artifactId}
  annotations:
    app.openshift.io/connects-to: my-database
  labels:
    app.kubernetes.io/part-of: fruit-service-app
    app.openshift.io/runtime: spring
spec:
  template:
    spec:
      containers:
        - env:
            - name: DEPLOYMENTCONFIG_POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                   name: my-database-secret
                   key: user
            - name: DEPLOYMENTCONFIG_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-database-secret
                  key: password
            - name: JAVA_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: fruit-service-configmap
                  key: java-options
